# PBX-ASL Engine


version: '2.4'
services:
    pbx-asl-user1:
        container_name: asl-user1
        cpu_shares: 512
        mem_reservation: 300m
        volumes:
            #Write Asterisk configuration outside container
            # - '/etc/asl/user1/conf/rpt.conf:/etc/asterisk/rpt.conf'
            # - '/etc/asl/user1/conf/extensions.conf:/etc/asterisk/extensions.conf'
            # - '/etc/asl/user1/conf/iax.conf:/etc/asterisk/iax.conf'
            # - '/etc/asl/user1/conf/modules.conf:/etc/asterisk/modules.conf'
            #Write logs files outside of container
            #SSH Authentication
              - '/etc/asl/user1/.ssh/authorized_keys:/root/.ssh/authroized_keys'
        ports:
            #SSH Port
            - '2221:22/tcp'
            #IAX Port
            - '4569:4569/udp'
        image: 'shaymez/pbx-asl-engine:latest'
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.10
        #Control markup inside container
        environment:
            #IPV6 support 
            - ASL_IPV6=0
        read_only: "true"

    pbx-asl-user2:
        container_name: asl-user2
        cpu_shares: 512
        mem_reservation: 300m
        volumes:
            #Write Asterisk configuration outside container
            # - '/etc/asl/user2/conf/rpt.conf:/etc/asterisk/rpt.conf'
            # - '/etc/asl/user2/conf/extensions.conf:/etc/asterisk/extensions.conf'
            # - '/etc/asl/user2/conf/iax.conf:/etc/asterisk/iax.conf'
            # - '/etc/asl/user1/conf/modules.conf:/etc/asterisk/modules.conf'
            #SSH Authentication
              - '/etc/asl/user2/.ssh/authorized_keys:/root/.ssh/authroized_keys'
            #Write logs files outside of container
         ports:
            #SSH Port
            - '2222:22/tcp'
            #IAX Port
            - '4570:4569/udp'
        image: 'shaymez/pbx-asl-engine:latest'
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.20
        #Control markup inside container
        environment:
            #IPV6 support 
            - ASL_IPV6=0
        read_only: "true"

    pbx-asl-user3:
        container_name: asl-user3
        cpu_shares: 512
        mem_reservation: 300m
        volumes:
            #Write Asterisk configuration outside container
            # - '/etc/asl/user3/conf/rpt.conf:/etc/asterisk/rpt.conf'
            # - '/etc/asl/user3/conf/extensions.conf:/etc/asterisk/extensions.conf'
            # - '/etc/asl/user3/conf/iax.conf:/etc/asterisk/iax.conf'
            # - '/etc/asl/user1/conf/modules.conf:/etc/asterisk/modules.conf'
            #SSH Authentication
              - '/etc/asl/user3/.ssh/authorized_keys:/root/.ssh/authroized_keys'
            #Write logs files outside of container
        ports:
            #SSH Port
            - '2223:22/tcp'
            #IAX Port
            - '4571:4569/udp'
        image: 'shaymez/pbx-asl-engine:latest'
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.30
        #Control markup inside container
        environment:
            #IPV6 support 
            - ASL_IPV6=0
        read_only: "true"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
